### ISSUE TITLE
great

### ISSUE THREAD

**Issue by oodvg** [Jack-Gledhill/captain#8]
Hey! This is similar to rowboat, but this is a great rewrite. maybe rewrite to discord.js and/or mongo or sqlite (for noobs). You dont have to download anything with mongo. With postgres, you would have to download its software to make a database.

**Comment by Vetlix** [comment]
Imagine using discord.js in 2020

**Comment by Jack-Gledhill** [comment]
> Hey! This is similar to rowboat, but this is a great rewrite. maybe rewrite to discord.js and/or mongo or sqlite (for noobs). You dont have to download anything with mongo. With postgres, you would have to download its software to make a database. 

First off, I didn't write this in Node.js because I don't want to and don't plan on doing so. Secondly I don't understand your point about Mongo. You need to install a Mongo server to be able to run one. Sure, there's Atlas but that would be limiting people's options. Not to mention Postgres is doing just fine as it is. I don't see any cause to rewrite for either scenario. 

If you really care enough, you could submit a pr with the rewrites and I could create a separate branch.

Thank you for the feedback though, I appreciate it.

**Comment by Zorotic** [comment]
Imagine not making your own custom use lib in 2020.

**Comment by Jack-Gledhill** [comment]
> Imagine not making your own custom use lib in 2020.

Imagine not making your own programming language in 2020

**Comment by Zorotic** [comment]
> > Imagine not making your own custom use lib in 2020.
> 
> Imagine not making your own programming language in 2020

Imagine not making your own kernel to run your own programming language on

**Comment by Zorotic** [comment]
IN 2020!

**Comment by Tazhys** [comment]
zoro wins lmfao

**Comment by Jack-Gledhill** [comment]
Imagine not making your own universe >:DDD
